coverage:
  status:
    project:
      default:
        target: 30%
        threshold: 5%
    patch:
      default:
        target: 5%
        threshold: 5%
ignore:
  - "api/handlers/dispute/model.go"
  - "api/handlers/workflow/model.go"
  - "api/handlers/ticket/model.go"
  - "api/middleware/jwt.go"
  - "api/main.go"
  - "api/models/utilityModels.go"
  - "api/db/db.go"
  - "api/redisDB/redis.go"
  - "api/models/models.go"
  - "api/models/responseModels.go"
  - "api/handlers/handlers.go"
  - "api/docs/docs.go"
