services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - "api"
    env_file:
      - fe.env
  api:
    build: ./api
    ports:
      - "8080:8080"
    env_file:
      - api.env
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
