services:
  frontend:
    image: dispute-resolution-engine-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - "api"
  api:
    image: dispute-resolution-engine-api:latest
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
      - "redis-cache"
    volumes:
      - evi_files:/app/filestorage       

  redis-cache:
    image: redis:latest
    ports:
      - "6379:6379"
    command: sh -c 'redis-server --requirepass "$$REDIS_PASSWORD"'

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d      
volumes:
  pgdata:
  evi_files: