# action.yml
name: 'Cypress Docker test'
description: 'Runs cypress in a docker container'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release
    types:
      - opened
      - reopened
runs:
  using: 'docker'
  image: 'Dockerfile'
