import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex h-full">
          <nav>
            <ul className=" w-56 p-2 flex flex-col h-full">
              <li>
                <Button variant="link" asChild>
                  <Link href="/disputes/1">Hello Sur!</Link>
                </Button>
              </li>
              <li>
                <Button variant="link" asChild>
                  <Link href="/disputes/2">You stole my lunch</Link>
                </Button>
              </li>
              <li>
                <Button variant="link" asChild>
                  <Link href="/disputes/3">You killed my family</Link>
                </Button>
              </li>
              <li className="mt-auto">
                <Button variant="secondary" asChild>
                  <Link href="/disputes/create" className="w-full">
                    + Create
                  </Link>
                </Button>
              </li>
            </ul>
          </nav>
          <Separator orientation="vertical" />
          <main className="grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
