name: End-to-end tests
on:
  workflow_run:
    workflows: "Deployment"
    types:
      - completed
jobs:
  cypress-test:
    container:
      image: cypress/included
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'http://capstone-dre.dns.net.za'
          wait-on-timeout: 300
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}