name: End-to-end tests
on:
  push:
    branches:
      - hotfix/cypress-test
  workflow_run:
    workflows: ["Deployment"]
    types:
      - completed
  workflow_dispatch:
    
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run a basic command
        run: echo "This is for workflow compliance"

  cypress-test:
    container:
      image: cypress/included
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20 
      # - name: Cache Node modules
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       frontend/node_modules
      #       ~/.cache/yarn
      #     key: yarn-${{ hashFiles('frontend/package.json') }}
      #     restore-keys: |
      #       yarn-${{ hashFiles('frontend/package.json') }}
      #       yarn-
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: 'frontend'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed

      - run: yarn install --frozen-lockfile

      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     working-directory: frontend 
      - run: yarn cypress run
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4.0.1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}