name: End-to-end tests
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/included
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start DB and API
        run: |
          docker compose build
          docker compose up -d

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend