name: Go Test
run-name: ${{ github.actor }} at ${{ github.event_name }} event 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release
      - dev
    types:
      - opened
      - reopened
jobs:
  go-test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run go test
        run: |
          cd api/__tests__
          go test