name: Go Test
run-name: ${{ github.actor }} at ${{ github.event_name }} event 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - release
      - dev
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  go-test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run go test
        run: |
          cd api
          go test ./... -v -race -covermode=atomic -coverprofile=coverage.out
          go-ignore-cov --file coverage.out
          go tool cover -func=coverage.out
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
