name: Jest-Test
run-name: ${{ github.actor }} at ${{ github.event_name }} event 
on:
  workflow_dispatch:
jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.3'
          cache: 'yarn' # This line enables caching for Yarn dependencies
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          cd frontend
          npm install -g yarn
          yarn
      - name: Run jest
        run: |
          cd frontend
          yarn test
        continue-on-error: true 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}