name: Jest-Test
run-name: ${{ github.actor }} at ${{ github.event_name }} event 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - release
      - dev
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  jest-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.3'
          cache-dependency-path: 'frontend/yarn.lock'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            frontend/node_modules
            ~/.cache/yarn
          key: yarn-${{ hashFiles('frontend/package.json') }}
          restore-keys: |
            yarn-
            - name: Run install
      - uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: 'frontend'

      - run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn nx affected -t lint test build